version: "3.9"
services:
  web:
    build: ./app
    ports:
      - 8000:5000
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  call:
    build: ./call_app
    ports:
      - 8080:5080
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
